### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jantenhove** [olivierhill/Spaduino#1]
First of all, thanks for doing the hard work on decoding the protocol.
I want to try to use your project as a starting base for controlling my spa. It has a display with more buttons and a different Balboa controller, but it also has 2 RJ45 connector, so I hope i can reuse (a part) of your code on the second connector.
I have a few questions:
- The balboa spa operates on 5V, the ATmega328P on 3.3V, yet the signals from the spa are directly connected to the Atmega inputs. Are those 3.3V?
- You did not connect the pins 2, 3 and 7. Just because you don't use them? I plan to connect them using the same resistor as the temperature button.

**Comment by olivierhill** [comment]
Depending on many buttons the top display has, it might or might not be a different protocol. Some use an SPI protocol instead of the proprietary 7-bit that was coded here.

As for your two questions, the Balboba does operate at 5V. The ATmega is not really 5V tolerant on 3.3V but the clock and data signal are mostly at 0V. If you were to feed a constant 5V it would fry the ATmega. If you really want to be safe you can pass these through a voltage divider or a CMOS voltage converter. A bunch of 78xx chips can be used for those. I've been running mine since 2016 constantly and it still works.

The other pins are for Pump 1&2 and Lights. You can see the pinout here: https://www.olivierhill.ca/archives/74-Cal-Spa-Connector.html

**Comment by olivierhill** [comment]
Depending on many buttons the top display has, it might or might not be a different protocol. Some use an SPI protocol instead of the proprietary 7-bit that was coded here.

As for your two questions, the Balboba does operate at 5V. The ATmega is not really 5V tolerant on 3.3V but the clock and data signal are mostly at 0V. If you were to feed a constant 5V it would fry the ATmega. If you really want to be safe you can pass these through a voltage divider or a CMOS voltage converter. A bunch of 78xx chips can be used for those. I've been running mine since 2016 constantly and it still works.

The other pins are for Pump 1&2 and Lights. You can see the pinout here: https://www.olivierhill.ca/archives/74-Cal-Spa-Connector.html
